/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package factura;

import javax.swing.table.DefaultTableModel;



/**
 *
 * @author housss
 */
public class Compilacion extends javax.swing.JFrame {

    /**
     * Creates new form Compilacion
     */
    public Compilacion() {
        initComponents();
        this.tabladetalles.setModel(modelo);
        this.modelo.addColumn("Nacionalidad");
        this.modelo.addColumn("Genero");
        this.modelo.addColumn("Tallas");
        this.modelo.addColumn("Prendas");
        this.modelo.addColumn("Cantidad");
        this.modelo.addColumn("Precio Unitario");
        this.modelo.addColumn("Total a Pagar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbonacionalidad = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        botonh = new javax.swing.JRadioButton();
        botonm = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cbotalla = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtprenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        btngenerar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladetalles = new javax.swing.JTable();
        btnlimpiartabla = new javax.swing.JButton();
        btnquitar = new javax.swing.JButton();
        btnnetopagar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtnetopagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Sistema Tienda de Ropa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Realiza Compra"));

        jLabel2.setText("Nacionalidad");

        cbonacionalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Seleccione]", "Peruano", "Extranjero" }));

        jLabel3.setText("Genero:");

        botonh.setText("Hombre");

        botonm.setText("Mujer");

        jLabel4.setText("Tallas:");

        cbotalla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Seleccione]", "S", "M", "L" }));

        jLabel5.setText("Prenda");

        jLabel6.setText("Cantidad");

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio");

        btngenerar.setText("Generar Compra");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        jLabel8.setText("Total a Pagar:");

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel3)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel6)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel7)
                        .addGap(91, 91, 91))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbonacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(botonh)
                                .addGap(18, 18, 18)
                                .addComponent(botonm)
                                .addGap(74, 74, 74)
                                .addComponent(cbotalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btngenerar)
                                .addGap(111, 111, 111)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnlimpiar)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbonacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonh)
                        .addComponent(botonm)
                        .addComponent(cbotalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnlimpiar)
                            .addComponent(btngenerar))
                        .addGap(33, 33, 33))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de Compra"));

        tabladetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladetalles);

        btnlimpiartabla.setText("Limpiar Tabla");
        btnlimpiartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiartablaActionPerformed(evt);
            }
        });

        btnquitar.setText("Quitar Compra");
        btnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarActionPerformed(evt);
            }
        });

        btnnetopagar.setText("Neto a Pagar");
        btnnetopagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnetopagarActionPerformed(evt);
            }
        });

        jLabel9.setText("Neto a Pagar S/. ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnlimpiartabla)
                        .addGap(87, 87, 87)
                        .addComponent(btnquitar)
                        .addGap(104, 104, 104)
                        .addComponent(btnnetopagar)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel9)
                        .addGap(34, 34, 34)
                        .addComponent(txtnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiartabla)
                    .addComponent(btnquitar)
                    .addComponent(btnnetopagar)
                    .addComponent(jLabel9)
                    .addComponent(txtnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 DefaultTableModel modelo=new DefaultTableModel();
    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        descuentos_hombres_peruanos();
        descuentos_mujeres_peruanas();
        descuentos_hombres_extranjeros();
        descuentos_mujeres_extranjeras();   
        
        if(botonh.isSelected()){
            this.modelo.addRow(new Object[]{this.cbonacionalidad.getSelectedItem(),"Hombre",
                this.cbotalla.getSelectedItem(),this.txtprenda.getText(),this.txtcantidad.getText(),
                this.txtprecio.getText(),this.txttotal.getText()});
        }
        else if(botonm.isSelected()){
            this.modelo.addRow(new Object[]{this.cbonacionalidad.getSelectedItem(),"Mujer",
                this.cbotalla.getSelectedItem(),this.txtprenda.getText(),this.txtcantidad.getText(),
                this.txtprecio.getText(),this.txttotal.getText()});
            
        }
    }//GEN-LAST:event_btngenerarActionPerformed
    
    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        this.cbonacionalidad.setSelectedIndex(0);
        if(botonh.isSelected()){
  
        }
        if(botonh.isSelected()){
            
        }
        this.cbotalla.setSelectedIndex(0);
        this.txtprenda.setText("");
        this.txtcantidad.setText("");
        this.txtprecio.setText("");
        this.txttotal.setText("");
        
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarActionPerformed
        // TODO add your handling code here:
        modelo.removeRow(this.tabladetalles.getSelectedRow());
    }//GEN-LAST:event_btnquitarActionPerformed

    private void btnlimpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartablaActionPerformed
        
        int x=this.modelo.getRowCount();
        for(int y=0; y <=x; y++){
            this.modelo.removeRow(0);
            
        }
        this.txtnetopagar.setText("");  
    }//GEN-LAST:event_btnlimpiartablaActionPerformed

    private void btnnetopagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnetopagarActionPerformed
        // TODO add your handling code here:
        double sumatoria;
        double sumatorial=0;
        int totalrow=tabladetalles.getRowCount();
        totalrow-=1;
        for(int  i=0; i<= (totalrow); i++){
            sumatoria=Double.parseDouble(String.valueOf(tabladetalles.getValueAt(i, 6)));
            sumatorial+=sumatoria;
        }
        txtnetopagar.setText("S.  "+String.valueOf(sumatorial));
        
    }//GEN-LAST:event_btnnetopagarActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    public void descuentos_hombres_extranjeros(){
        double cantidad_s,precio_s,total_s,desc_s=0.04;
        double  cantidad_m,precio_m,total_m,desc_m=0.09;
        double cantidad_l,precio_l,total_l,desc_l=0.12;
        
        if (cbonacionalidad.getSelectedIndex()==2){
            if(this.botonh.isSelected()){
                if (cbotalla.getSelectedIndex()==1){
                    cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                    precio_s=Double.parseDouble(this.txtcantidad.getText());
                    total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                    
                }
            }
        }
        if (cbonacionalidad.getSelectedIndex()==2){
            if(this.botonh.isSelected()){
                if(cbotalla.getSelectedIndex()==2){
                    cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                    precio_m=Double.parseDouble(this.txtprecio.getText());
                    total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                        this.txttotal.setText(String.valueOf(total_m) );
                        
                }
            }
        }
         if (cbonacionalidad.getSelectedIndex()==2){
            if(this.botonh.isSelected()){
                if(cbotalla.getSelectedIndex()==3){
                    cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                    precio_l=Double.parseDouble(this.txtprecio.getText());
                    total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                        this.txttotal.setText(String.valueOf(total_l) );
    }
            }
         }
         
    }
    
    public void descuentos_mujeres_extranjeras(){
        Double cantidad_s,precio_s,total_s,desc_s=0.05;
        Double cantidad_m,precio_m,total_m,desc_m=0.07;
        Double cantidad_l,precio_l,total_l,desc_l=0.10;
        
        
        if(cbonacionalidad.getSelectedIndex()==2){
            if(this.botonm.isSelected()){
                if(cbotalla.getSelectedIndex()==1){
                    cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                    precio_s=Double.parseDouble(this.txtprecio.getText());
                    total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                    
                }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==2){
            if(this.botonm.isSelected()){
                if(cbotalla.getSelectedIndex()==2){
                    cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                    precio_m=Double.parseDouble(this.txtprecio.getText());
                    total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                    
                }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==2){
            if(this.botonm.isSelected()){
                if(cbotalla.getSelectedIndex()==3){
                    cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                    precio_l=Double.parseDouble(this.txtprecio.getText());
                    total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                    
                }
            }
        }
    }
    
    public void descuentos_mujeres_peruanas(){
        double cantidad_s,precio_s,total_s,desc_s=0.04;
        double cantidad_m,precio_m,total_m,desc_m=0.09;
        double cantidad_l,precio_l,total_l,desc_l=0.12;
        
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotalla.getSelectedIndex()==1){
                    cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                    precio_s=Double.parseDouble(this.txtprecio.getText());
                    total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                    
                }
            }
        }
        
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotalla.getSelectedIndex()==2){
                    cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                    precio_m=Double.parseDouble(this.txtprecio.getText());
                    total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                    
                }
            }
        }
        
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotalla.getSelectedIndex()==3){
                    cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                    precio_l=Double.parseDouble(this.txtprecio.getText());
                    total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                    
                }
            }
        }
    }
    
    public void descuentos_hombres_peruanos(){
        double cantidad_s,precio_s,total_s,desc_s=0.05;
        double cantidad_m,precio_m,total_m,desc_m=0.07;
        double cantidad_l,precio_l,total_l,desc_l=0.10;
        
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonh.isSelected()){
                if(cbotalla.getSelectedIndex()==1){
                    cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                    precio_s=Double.parseDouble(this.txtprecio.getText());
                    total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                    
                }
            }
        }
        
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonh.isSelected()){
                if(cbotalla.getSelectedIndex()==2){
                    cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                    precio_m=Double.parseDouble(this.txtprecio.getText());
                    total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                    
                }
            }
        }
        
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonh.isSelected()){
                if(cbotalla.getSelectedIndex()==3){
                    cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                    precio_l=Double.parseDouble(this.txtprecio.getText());
                    total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
            
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compilacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonh;
    private javax.swing.JRadioButton botonm;
    private javax.swing.JButton btngenerar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnlimpiartabla;
    private javax.swing.JButton btnnetopagar;
    private javax.swing.JButton btnquitar;
    private javax.swing.JComboBox cbonacionalidad;
    private javax.swing.JComboBox cbotalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladetalles;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtnetopagar;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprenda;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}

